//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetCRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MISSIONJOUR
    {
        public int IDJOUR { get; set; }
        public string MISSION_CODE { get; set; }
        public string ETAT { get; set; }
        public System.DateTime JOUR { get; set; }
        public double TEMPS_ACCORDE { get; set; }
    
        public virtual MISSION MISSION { get; set; }
    }
}
